package myChat.chat;


import Pages.Interface;
import java.awt.Color;
import java.io.*;
import java.net.Socket;
import java.util.ArrayList;
import javax.swing.ImageIcon;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author acer
 */
public class theClient extends javax.swing.JFrame {

//    Source OOP = new Source();
    private String username;
    private ArrayList<String> users = new ArrayList();

    private Boolean isConnected = false;

    private Socket theSocket;
    private BufferedReader theReader;
    private PrintWriter theWriter;
    private Interface infa = null;
    private int xMouse;
    private int yMouse;
    
    public void ListenThread() {
        Thread IncomingReader = new Thread(new Message());
        IncomingReader.start();
    }

    public void userAdd(String data) {
        users.add(data);
    }

    public void userRemove(String data) {
        sentMessage.append(data + " is now offline.\n");
    }

    public void writeUsers() {
        String[] tempList = new String[(users.size())];
        users.toArray(tempList);
        for (String token : tempList) {

        }
    }

    public void sendDisconnect() {
        String bye = (username + ": :Disconnect");
        try {
            theWriter.println(bye);
            theWriter.flush();
        } catch (Exception e) {
            sentMessage.append("You're not connected.\n");
        }
    }

    public void Disconnect() {
        try {
            sentMessage.append("Disconnected.\n");
            theSocket.close();
        } catch (Exception ex) {

        }
        isConnected = false;
    }
    
    public theClient(Interface Infa) {
        initComponents();
        setLocation(1170,300);
        infa=Infa;
        username = infa.getName();
        client_Name.setText(username);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        connect_Panel = new javax.swing.JPanel();
        connect = new javax.swing.JLabel();
        disconnect_Panel = new javax.swing.JPanel();
        disConnect = new javax.swing.JLabel();
        clientname_panel = new javax.swing.JPanel();
        client_Name = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        send_Panel = new javax.swing.JPanel();
        Send = new javax.swing.JLabel();
        Message = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        sentMessage = new javax.swing.JTextArea();
        header_panel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        close_Panel = new javax.swing.JPanel();
        close_label = new javax.swing.JLabel();
        min_Panel = new javax.swing.JPanel();
        min = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(85, 65, 118));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 33, 89), 1, true));

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        connect_Panel.setBackground(new java.awt.Color(54, 33, 89));

        connect.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        connect.setForeground(new java.awt.Color(204, 204, 204));
        connect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        connect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/images/icons8_connected_32px.png"))); // NOI18N
        connect.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                connectMouseMoved(evt);
            }
        });
        connect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                connectMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                connectMouseExited(evt);
            }
        });

        javax.swing.GroupLayout connect_PanelLayout = new javax.swing.GroupLayout(connect_Panel);
        connect_Panel.setLayout(connect_PanelLayout);
        connect_PanelLayout.setHorizontalGroup(
            connect_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(connect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        connect_PanelLayout.setVerticalGroup(
            connect_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(connect, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(connect_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 40, 50));

        disconnect_Panel.setBackground(new java.awt.Color(54, 33, 89));

        disConnect.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        disConnect.setForeground(new java.awt.Color(204, 204, 204));
        disConnect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/images/icons8_disconnected_32px_2.png"))); // NOI18N
        disConnect.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                disConnectMouseMoved(evt);
            }
        });
        disConnect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disConnectMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                disConnectMouseExited(evt);
            }
        });

        javax.swing.GroupLayout disconnect_PanelLayout = new javax.swing.GroupLayout(disconnect_Panel);
        disconnect_Panel.setLayout(disconnect_PanelLayout);
        disconnect_PanelLayout.setHorizontalGroup(
            disconnect_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(disConnect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        disconnect_PanelLayout.setVerticalGroup(
            disconnect_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(disConnect, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(disconnect_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 40, 50));

        clientname_panel.setBackground(new java.awt.Color(54, 33, 89));

        client_Name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        client_Name.setForeground(new java.awt.Color(204, 204, 204));
        client_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        client_Name.setText("Name");

        javax.swing.GroupLayout clientname_panelLayout = new javax.swing.GroupLayout(clientname_panel);
        clientname_panel.setLayout(clientname_panelLayout);
        clientname_panelLayout.setHorizontalGroup(
            clientname_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(client_Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        clientname_panelLayout.setVerticalGroup(
            clientname_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientname_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(client_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(clientname_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 160, 50));

        jPanel6.setBackground(new java.awt.Color(70, 47, 110));

        send_Panel.setBackground(new java.awt.Color(70, 47, 110));

        Send.setBackground(new java.awt.Color(70, 47, 110));
        Send.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/images/icons8_send_letter_32px.png"))); // NOI18N
        Send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SendMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SendMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SendMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout send_PanelLayout = new javax.swing.GroupLayout(send_Panel);
        send_Panel.setLayout(send_PanelLayout);
        send_PanelLayout.setHorizontalGroup(
            send_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Send, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );
        send_PanelLayout.setVerticalGroup(
            send_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Message.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Message.setText("Your messages");
        Message.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Message.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MessageKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MessageKeyReleased(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 2, new java.awt.Color(54, 33, 89)));

        sentMessage.setEditable(false);
        sentMessage.setColumns(20);
        sentMessage.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        sentMessage.setRows(5);
        sentMessage.setBorder(null);
        jScrollPane1.setViewportView(sentMessage);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(send_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Message)
                    .addComponent(send_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        header_panel.setBackground(new java.awt.Color(54, 33, 89));
        header_panel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        header_panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header_panelMouseDragged(evt);
            }
        });
        header_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header_panelMousePressed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/images/icons8_chat_24px.png"))); // NOI18N

        close_Panel.setBackground(new java.awt.Color(54, 33, 89));

        close_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        close_label.setForeground(new java.awt.Color(204, 204, 204));
        close_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close_label.setText("X");
        close_label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                close_labelMouseMoved(evt);
            }
        });
        close_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_labelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_labelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout close_PanelLayout = new javax.swing.GroupLayout(close_Panel);
        close_Panel.setLayout(close_PanelLayout);
        close_PanelLayout.setHorizontalGroup(
            close_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );
        close_PanelLayout.setVerticalGroup(
            close_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        min_Panel.setBackground(new java.awt.Color(54, 33, 89));

        min.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        min.setForeground(new java.awt.Color(204, 204, 204));
        min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/images/icons8_subtract_22px.png"))); // NOI18N
        min.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                minMouseMoved(evt);
            }
        });
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
        });

        javax.swing.GroupLayout min_PanelLayout = new javax.swing.GroupLayout(min_Panel);
        min_Panel.setLayout(min_PanelLayout);
        min_PanelLayout.setHorizontalGroup(
            min_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, min_PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        min_PanelLayout.setVerticalGroup(
            min_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(min, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout header_panelLayout = new javax.swing.GroupLayout(header_panel);
        header_panel.setLayout(header_panelLayout);
        header_panelLayout.setHorizontalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addComponent(min_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(close_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        header_panelLayout.setVerticalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(close_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(min_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(header_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void disConnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disConnectMouseClicked
        connect.setIcon(new ImageIcon(getClass().getResource("/Home/images/icons8_connected_32px.png")));
        sendDisconnect();
        Disconnect();
    }//GEN-LAST:event_disConnectMouseClicked

    private void SendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendMouseClicked
        
        switch (Message.getText()) {
            case "Your messages":
                Message.setText("Type your message here");
                Message.requestFocus();
                break;
            case "Client name":
                break;
            case "Input yuor name":
                break;
            default:
              try {
                theWriter.println(username + " : " + Message.getText() + ":" + "Chat");
                theWriter.flush();
            } catch (Exception ex) {
                sentMessage.append("You're not connected. \n");
            }
            Message.setText("");
            Message.requestFocus();

        }

        Message.setText("Your messages");
        Message.requestFocus();
    }//GEN-LAST:event_SendMouseClicked

    private void MessageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MessageKeyPressed

        if (Message.getText().equals("Your messages"))
            Message.setText("");
    }//GEN-LAST:event_MessageKeyPressed

    private void disConnectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disConnectMouseExited
        disconnect_Panel.setBackground(new Color(54,33,89));
    }//GEN-LAST:event_disConnectMouseExited

    private void MessageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MessageKeyReleased
        switch (client_Name.getText()) {
            case "":
                client_Name.setText("client name");
                break;
            default:
                String name = client_Name.getText();
                String result = name.substring(0, 1).toUpperCase() + name.substring(1);
                client_Name.setText(result);
       
        }
    }//GEN-LAST:event_MessageKeyReleased

    private void disConnectMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disConnectMouseMoved
        disconnect_Panel.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_disConnectMouseMoved

    private void connectMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectMouseMoved
        connect_Panel.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_connectMouseMoved

    private void connectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectMouseExited
        connect_Panel.setBackground(new Color(54,33,89));
    }//GEN-LAST:event_connectMouseExited

    private void connectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectMouseClicked
  
        if (isConnected == false) {

            try {
                theSocket = new Socket(infa.ipaddress, 3000);
                InputStreamReader streamreader = new InputStreamReader(theSocket.getInputStream());
                theReader = new BufferedReader(streamreader);
                theWriter = new PrintWriter(theSocket.getOutputStream());
                theWriter.println(username + ": has connected :Connect");
                theWriter.flush();
                isConnected = true;
                connect.setIcon(new ImageIcon(getClass().getResource("/Home/images/icons8_connected_32px_1.png")));

            } catch (Exception ex) {
                sentMessage.append("Cannot Connect! Try Again. \n");
                connect.setIcon(new ImageIcon(getClass().getResource("/Home/images/icons8_connected_32px.png")));

            }
            ListenThread();

        } else if (isConnected == true) {
            sentMessage.append("You are connected. \n");
        } 
    }//GEN-LAST:event_connectMouseClicked

    private void SendMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendMousePressed
        Send.setIcon(new ImageIcon(getClass().getResource("/Home/images/icons8_send_letter_32px_1.png")));
    }//GEN-LAST:event_SendMousePressed

    private void SendMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendMouseReleased
        Send.setIcon(new ImageIcon(getClass().getResource("/Home/images/icons8_send_letter_32px.png")));
    }//GEN-LAST:event_SendMouseReleased

    private void close_labelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_labelMouseMoved
        close_Panel.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_close_labelMouseMoved

    private void close_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_labelMouseClicked
        infa.client_started=false;
        dispose();
    }//GEN-LAST:event_close_labelMouseClicked

    private void close_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_labelMouseExited
        close_Panel.setBackground(new Color(54,33,89));
    }//GEN-LAST:event_close_labelMouseExited

    private void minMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseMoved
        min_Panel.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_minMouseMoved

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        setExtendedState(this.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
        min_Panel.setBackground(new Color(54,33,89));
    }//GEN-LAST:event_minMouseExited

    private void header_panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_panelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_header_panelMouseDragged

    private void header_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_panelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_header_panelMousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Message;
    private javax.swing.JLabel Send;
    private javax.swing.JLabel client_Name;
    private javax.swing.JPanel clientname_panel;
    private javax.swing.JPanel close_Panel;
    private javax.swing.JLabel close_label;
    private javax.swing.JLabel connect;
    private javax.swing.JPanel connect_Panel;
    private javax.swing.JLabel disConnect;
    private javax.swing.JPanel disconnect_Panel;
    private javax.swing.JPanel header_panel;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel min;
    private javax.swing.JPanel min_Panel;
    private javax.swing.JPanel send_Panel;
    private javax.swing.JTextArea sentMessage;
    // End of variables declaration//GEN-END:variables
 public class Message implements Runnable {

        @Override
        public void run() {
            String[] data;
            String stream;

            try {
                while (!(stream = theReader.readLine()).equals(null)) {
                    data = stream.split(":");

                    switch (data[2]) {
                        case "Chat":
                            sentMessage.append(data[0] + ":" + data[1] + "\n");
                            sentMessage.setCaretPosition(sentMessage.getDocument().getLength());
                            break;
                        case "Connnect":
                            sentMessage.removeAll();
                            userAdd(data[0]);
                            break;
                        case "Disconnect":
                            userRemove(data[0]);
                            break;
                        case "Done":
                            writeUsers();
                            users.clear();
                    }
                }
            } catch (Exception ex) {
            }
        }
    }
}
